// flow-typed signature: 04f0044dbfda40be1b7f6285b7c5c44e
// flow-typed version: <<STUB>>/babel-plugin-ramda_v^1.2.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-ramda'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-ramda' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-ramda/lib/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-ramda/lib/modules' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-ramda/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-ramda/lib/index'>;
}
declare module 'babel-plugin-ramda/lib/modules.js' {
  declare module.exports: $Exports<'babel-plugin-ramda/lib/modules'>;
}
